// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvohdyaSL2ciCdMFG0XjqleKAVDP95X1s',
    appId: '1:658971748459:web:ccebde7bb43b773c2fa92e',
    messagingSenderId: '658971748459',
    projectId: 'loom-social',
    authDomain: 'loom-social.firebaseapp.com',
    storageBucket: 'loom-social.firebasestorage.app',
    measurementId: 'G-W2C6DCQ4NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEe28xgu8Xro0GJ6jvaeDmy2XCwK6C7RY',
    appId: '1:658971748459:android:44ac7191c60f3e622fa92e',
    messagingSenderId: '658971748459',
    projectId: 'loom-social',
    storageBucket: 'loom-social.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEW3jDP9s_XKrbfw5jNswe88jUydy6kvY',
    appId: '1:658971748459:ios:d569727a509d16d42fa92e',
    messagingSenderId: '658971748459',
    projectId: 'loom-social',
    storageBucket: 'loom-social.firebasestorage.app',
    iosBundleId: 'com.rudra.loom',
  );
}
